"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { VantageSelect } from "@/components/ui/vantage-select";

type Intelligence = { summary: string; seniority?: string; mustHave: string[]; niceToHave: string[]; skills: string[]; experience?: string; education?: string; responsibilities: string[]; locationRequirement?: string; remotePolicy?: string; applicationAdvice: string[]; unknowns: string[]; confidence: number; provider?: string; model?: string; source?: "ai" | "evidence" };
type ContactEvidence = { value: string; url: string; reason: string };
type Job = { id: string; title: string; companyName: string; companyWebsite?: string; companyDomain?: string; companyPhone?: string; companyEmail?: string; companyContactUrl?: string; companyContactEvidence?: ContactEvidence[]; location?: string; countryCode?: string; employmentType?: string; remote?: boolean; salaryMin?: number; salaryMax?: number; salaryCurrency?: string; postedAt?: string; applyUrl?: string; sourceUrl?: string; sourceName?: string; requirements?: string[]; intelligence?: Intelligence; verificationStatus: "direct_employer_verified" | "needs_verification" | "unverified" | "rejected" | "stale"; verificationScore?: number; verificationReasons: string[] };
type ProviderState = { provider: string; status: "queued" | "searching" | "researching" | "complete" | "failed"; count: number; totalCount?: number; errorMessage?: string };
type StreamEvent = { type: "status" | "provider" | "complete"; message?: string; provider?: string; jobs?: Job[]; providers: ProviderState[]; diagnostics?: Record<string, unknown>; pagination?: Record<string, { totalCount?: number; nextCursor?: string; hasMore: boolean }> };
type EnrichmentProgress = { status: "idle" | "running" | "complete" | "partial"; total: number; processed: number; aiAnalyzed: number; evidenceReady: number };

const countries = [["US", "United States"], ["NG", "Nigeria"], ["GB", "United Kingdom"], ["CA", "Canada"], ["DE", "Germany"], ["AU", "Australia"], ["FR", "France"], ["NL", "Netherlands"], ["IE", "Ireland"], ["ZA", "South Africa"]] as const;
const providers = ["adzuna", "jsearch", "jobspipe", "hirebase", "theirstack"];
const statusCopy = { direct_employer_verified: "Direct employer verified", needs_verification: "Needs verification", unverified: "Discovered", rejected: "Verification rejected", stale: "Listing may be stale" } as const;
const pageSize = 12;
const countryOptions = countries.map(([value, label]) => ({ value, label }));
const postedOptions = [{ value: "1", label: "1 day" }, { value: "7", label: "7 days" }, { value: "30", label: "30 days" }, { value: "90", label: "90 days" }];

function money(job: Job) { if (job.salaryMin == null && job.salaryMax == null) return "Salary not disclosed"; const currency = job.salaryCurrency ?? "USD"; const format = (n: number) => { try { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(n); } catch { return `${currency} ${Math.round(n).toLocaleString()}`; } }; return job.salaryMin != null && job.salaryMax != null ? `${format(job.salaryMin)} – ${format(job.salaryMax)}` : format(job.salaryMin ?? job.salaryMax!); }
function timeAgo(value?: string) { if (!value) return "Posting date unavailable"; const time = new Date(value).getTime(); if (!Number.isFinite(time)) return "Posting date unavailable"; const hours = Math.floor(Math.max(0, Date.now() - time) / 3600000); if (hours < 1) return "Posted just now"; if (hours < 24) return `${hours}h ago`; const days = Math.floor(hours / 24); return days === 1 ? "Yesterday" : `${days}d ago`; }
function mergeJobs(current: Job[], incoming: Job[]) { const map = new Map(current.map((job) => [job.id, job])); for (const job of incoming) { const old = map.get(job.id); map.set(job.id, old ? { ...old, ...job, companyPhone: job.companyPhone ?? old.companyPhone, companyEmail: job.companyEmail ?? old.companyEmail, companyWebsite: job.companyWebsite ?? old.companyWebsite, companyDomain: job.companyDomain ?? old.companyDomain, applyUrl: job.applyUrl ?? old.applyUrl } : job); } return Array.from(map.values()); }

function JobCard({ job, fresh, researching }: { job: Job; fresh?: boolean; researching: boolean }) {
  const intel = job.intelligence; const requirements = intel?.mustHave?.length ? intel.mustHave : job.requirements ?? []; const applicationUrl = job.applyUrl ?? (job.verificationStatus === "direct_employer_verified" ? job.companyWebsite : undefined); const contactEvidence = job.companyContactEvidence ?? [];
  return <article className={`overflow-hidden rounded-[22px] border border-white/10 bg-white/[.018] shadow-[0_20px_60px_rgba(0,0,0,.18)] ${fresh ? "vantage-job-arrival" : ""}`}><div className="p-5 md:p-6">
    <div className="flex flex-col gap-5 lg:flex-row lg:justify-between"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] text-white/55">{statusCopy[job.verificationStatus]}</span><span className="text-[10px] text-white/25">Evidence {job.verificationScore ?? 0}/100</span>{intel && <span className="rounded-full border border-white/10 bg-white/[.035] px-2.5 py-1 text-[10px] text-white/55">{intel.source === "ai" ? `AI confidence ${intel.confidence}%` : `Evidence confidence ${intel.confidence}%`}</span>}</div><h3 className="text-xl font-medium tracking-[-.025em]">{job.title}</h3><div className="mt-1 text-sm text-white/55">{job.companyName}</div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-white/35"><span>{job.location ?? "Location not disclosed"}</span><span>{job.employmentType ?? "Employment type not disclosed"}</span><span>{timeAgo(job.postedAt)}</span></div></div><div className="lg:text-right"><div className="text-sm font-medium">{money(job)}</div><div className="mt-1 text-[10px] text-white/25">{job.sourceName ?? "Live source"}</div></div></div>
    <div className="mt-6 grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-white/[.08] bg-black/20 p-4"><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">What the employer is asking for</div><p className="mt-2 text-sm leading-6 text-white/70">{intel?.summary ?? "Vantage is assembling evidence from the live listing."}</p>{requirements.length > 0 && <><div className="mt-4 text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">Must-have requirements</div><ul className="mt-2 grid gap-2 text-sm text-white/65 md:grid-cols-2">{requirements.slice(0, 10).map((item, index) => <li key={index}>• {item}</li>)}</ul></>}{intel?.niceToHave?.length ? <><div className="mt-4 text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">Preferred</div><ul className="mt-2 grid gap-2 text-sm text-white/50 md:grid-cols-2">{intel.niceToHave.slice(0, 8).map((item, index) => <li key={index}>• {item}</li>)}</ul></> : null}{intel?.skills?.length ? <div className="mt-4 flex flex-wrap gap-1.5">{intel.skills.slice(0, 12).map((skill) => <span key={skill} className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-white/45">{skill}</span>)}</div> : null}</div>
      <div className="rounded-2xl border border-white/[.08] bg-black/20 p-4"><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/30">Candidate intelligence</div>{intel?.seniority && <div className="mt-3 text-sm"><span className="text-white/30">Level · </span><span className="text-white/65">{intel.seniority}</span></div>}{intel?.experience && <div className="mt-2 text-sm"><span className="text-white/30">Experience · </span><span className="text-white/65">{intel.experience}</span></div>}{intel?.education && <div className="mt-2 text-sm"><span className="text-white/30">Education · </span><span className="text-white/65">{intel.education}</span></div>}{intel?.locationRequirement && <div className="mt-2 text-sm"><span className="text-white/30">Location · </span><span className="text-white/65">{intel.locationRequirement}</span></div>}{intel?.remotePolicy && <div className="mt-2 text-sm"><span className="text-white/30">Remote · </span><span className="text-white/65">{intel.remotePolicy}</span></div>}{intel?.responsibilities?.length ? <div className="mt-4 border-t border-white/[.07] pt-3"><div className="text-[10px] uppercase tracking-[.16em] text-white/25">Role responsibilities</div><ul className="mt-2 space-y-1 text-xs text-white/45">{intel.responsibilities.slice(0, 5).map((item, index) => <li key={index}>• {item}</li>)}</ul></div> : null}{intel?.unknowns?.length ? <div className="mt-4 border-t border-white/[.07] pt-3"><div className="text-[10px] uppercase tracking-[.16em] text-white/25">Still unknown</div><ul className="mt-2 space-y-1 text-xs text-white/40">{intel.unknowns.slice(0, 5).map((item, index) => <li key={index}>• {item}</li>)}</ul></div> : null}</div></div>
    {contactEvidence.length > 0 && <div className="mt-5 rounded-2xl border border-emerald-400/10 bg-emerald-400/[.035] p-4"><div className="text-[10px] font-semibold uppercase tracking-[.18em] text-emerald-200/45">Public employer contact</div><div className="mt-3 flex flex-wrap gap-2">{job.companyPhone && <a href={`tel:${job.companyPhone}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70">Call {job.companyPhone}</a>}{job.companyEmail && <a href={`mailto:${job.companyEmail}`} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70">Email {job.companyEmail}</a>}{job.companyContactUrl && <a href={job.companyContactUrl} target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/50">Contact page</a>}</div><div className="mt-2 text-[11px] text-white/25">Only public employer-domain contact evidence is shown. Vantage does not invent or infer contact information.</div></div>}
    <div className="mt-5 flex flex-col gap-3 border-t border-white/[.07] pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="text-xs text-white/30">{job.companyDomain ? `Employer source: ${job.companyDomain}` : "Employer source not established"}{job.sourceName?.toLowerCase().includes("adzuna") && <span className="ml-2">· Jobs by Adzuna</span>}</div><div className="flex flex-wrap gap-2">{applicationUrl && <a href={applicationUrl} target="_blank" rel="noreferrer" className="rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Open application</a>}{!applicationUrl && job.companyWebsite && <a href={job.companyWebsite} target="_blank" rel="noreferrer" className="rounded-xl border border-white/15 px-4 py-2.5 text-xs font-medium text-white/70">Visit employer</a>}{!applicationUrl && !job.companyWebsite && <span className={`rounded-xl border border-white/10 px-4 py-2.5 text-xs ${researching ? "text-white/55" : "text-white/30"}`}>{researching ? "Vantage is researching the employer application path…" : "No verified application path found after public-source research"}</span>}</div></div><div className="mt-3 text-[11px] text-white/25">Vantage never turns a third-party job-board redirect into an employer application link. Public-source research must establish the destination first.</div>
  </div></article>;
}

export default function JobsLivePage() {
  const [title, setTitle] = useState(""); const [location, setLocation] = useState(""); const [country, setCountry] = useState("US"); const [remote, setRemote] = useState(false); const [days, setDays] = useState("30"); const [directOnly, setDirectOnly] = useState(false);
  const [jobs, setJobs] = useState<Job[]>([]); const [providerStates, setProviderStates] = useState<ProviderState[]>(providers.map((provider) => ({ provider, status: "queued", count: 0 }))); const [pagination, setPagination] = useState<Record<string, { totalCount?: number; nextCursor?: string; hasMore: boolean }>>({});
  const [searching, setSearching] = useState(false); const [researching, setResearching] = useState(false); const [error, setError] = useState(""); const [resultPage, setResultPage] = useState(1); const [enrichment, setEnrichment] = useState<EnrichmentProgress>({ status: "idle", total: 0, processed: 0, aiAnalyzed: 0, evidenceReady: 0 }); const [newIds, setNewIds] = useState<Set<string>>(new Set());
  const abortRef = useRef<AbortController | null>(null); const enrichRunRef = useRef(0);
  const visibleJobs = useMemo(() => jobs.filter((job) => !directOnly || job.verificationStatus === "direct_employer_verified"), [jobs, directOnly]); const resultPages = Math.max(1, Math.ceil(visibleJobs.length / pageSize)); const pageJobs = visibleJobs.slice((resultPage - 1) * pageSize, resultPage * pageSize); const discoveredCount = jobs.length; const sourceCount = jobs.filter((job) => Boolean(job.companyWebsite)).length; const applicationCount = jobs.filter((job) => Boolean(job.applyUrl)).length; const contactCount = jobs.filter((job) => Boolean(job.companyPhone || job.companyEmail)).length;
  useEffect(() => { if (resultPage > resultPages) setResultPage(resultPages); }, [resultPage, resultPages]);

  async function enrichInBackground(targetJobs: Job[]) { if (!targetJobs.length) { setEnrichment({ status: "complete", total: 0, processed: 0, aiAnalyzed: 0, evidenceReady: 0 }); setResearching(false); return; } const run = ++enrichRunRef.current; const ids = targetJobs.map((job) => job.id); let offset = 0, processed = 0, aiAnalyzed = 0, evidenceReady = 0; setResearching(true); setEnrichment({ status: "running", total: ids.length, processed: 0, aiAnalyzed: 0, evidenceReady: 0 }); while (offset < ids.length && run === enrichRunRef.current) { try { const response = await fetch("/api/jobs/enrich", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids, offset }), cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Deep research failed"); const enriched = Array.isArray(body.jobs) ? body.jobs as Job[] : []; setJobs((current) => mergeJobs(current, enriched)); processed += Number(body.processed ?? 0); aiAnalyzed += Number(body.aiAnalyzed ?? 0); evidenceReady += Number(body.evidenceReady ?? enriched.length); offset = Number(body.nextOffset ?? ids.length); setEnrichment({ status: "running", total: ids.length, processed, aiAnalyzed, evidenceReady }); } catch { setEnrichment({ status: "partial", total: ids.length, processed, aiAnalyzed, evidenceReady }); setResearching(false); return; } } if (run === enrichRunRef.current) { setEnrichment({ status: "complete", total: ids.length, processed, aiAnalyzed, evidenceReady }); setResearching(false); } }

  async function searchLive(event?: FormEvent) { event?.preventDefault(); if (!title.trim() || searching) return; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setSearching(true); setResearching(true); setError(""); setJobs([]); setNewIds(new Set()); setResultPage(1); setPagination({}); setProviderStates(providers.map((provider) => ({ provider, status: "queued", count: 0 }))); setEnrichment({ status: "idle", total: 0, processed: 0, aiAnalyzed: 0, evidenceReady: 0 }); try { const response = await fetch("/api/jobs/search/stream", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/x-ndjson" }, body: JSON.stringify({ title: title.trim(), city: location.trim() || undefined, country: countries.find(([code]) => code === country)?.[1], countryCode: country, remote, postedWithinDays: Number(days), limit: 50, page: 1 }), signal: controller.signal, cache: "no-store" }); if (!response.ok || !response.body) { const body = await response.json().catch(() => ({})); throw new Error(body.error ?? "Live job discovery is unavailable."); } const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = "", firstResults = false, finalJobs: Job[] = []; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; let eventData: StreamEvent; try { eventData = JSON.parse(line) as StreamEvent; } catch { continue; } if (eventData.providers) setProviderStates(eventData.providers); if (eventData.type === "provider" && eventData.jobs) { setJobs((current) => { const merged = mergeJobs(current, eventData.jobs!); const incomingIds = new Set(eventData.jobs!.filter((job) => !current.some((old) => old.id === job.id)).map((job) => job.id)); if (incomingIds.size) setNewIds(incomingIds); return merged; }); if (!firstResults && eventData.jobs.length) { firstResults = true; setSearching(false); } } if (eventData.type === "complete") { finalJobs = eventData.jobs ?? []; setJobs(finalJobs); setPagination(eventData.pagination ?? {}); setSearching(false); } } } if (buffer.trim()) { try { const eventData = JSON.parse(buffer) as StreamEvent; if (eventData.type === "complete") { finalJobs = eventData.jobs ?? finalJobs; setJobs(finalJobs); setPagination(eventData.pagination ?? {}); } } catch {} } setSearching(false); if (finalJobs.length) void enrichInBackground(finalJobs); else setResearching(false); } catch (cause) { if ((cause as Error)?.name === "AbortError") return; setSearching(false); setResearching(false); setError(cause instanceof Error ? cause.message : "Live job discovery failed."); } }

  async function loadMore() { if (searching) return; const nextPage = resultPage + 1; if (nextPage > resultPages && !Object.values(pagination).some((item) => item.hasMore)) return; try { const response = await fetch("/api/jobs/search/stream", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/x-ndjson" }, body: JSON.stringify({ title: title.trim(), city: location.trim() || undefined, country: countries.find(([code]) => code === country)?.[1], countryCode: country, remote, postedWithinDays: Number(days), limit: 50, page: nextPage }), cache: "no-store" }); if (!response.ok || !response.body) return; const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = "", latest: Job[] = []; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.trim()) continue; try { const eventData = JSON.parse(line) as StreamEvent; if (eventData.providers) setProviderStates(eventData.providers); if (eventData.type === "provider" && eventData.jobs) { latest = eventData.jobs; setJobs((current) => mergeJobs(current, eventData.jobs!)); } if (eventData.type === "complete") { latest = eventData.jobs ?? latest; setPagination(eventData.pagination ?? {}); } } catch {} } } setResultPage(nextPage); if (latest.length) void enrichInBackground(latest); } catch {} }

  return <main className="mx-auto min-h-screen w-full max-w-6xl px-4 pb-24 pt-8 md:px-6 md:pt-12">
    <header className="mb-8"><div className="section-label">Vantage / Job Intelligence</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Find the opportunity. <span className="text-white/35">Find the employer.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">Vantage searches multiple live job sources, resolves employer identity, and builds evidence-backed application paths and public contact options.</p></header>
    <form onSubmit={searchLive} className="rounded-[24px] border border-white/10 bg-white/[.025] p-3 shadow-[0_30px_90px_rgba(0,0,0,.2)]"><div className="grid gap-3 md:grid-cols-[1.3fr_.8fr_.55fr_auto]"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Job title, role, or skill" autoComplete="off" className="h-12 rounded-xl border border-white/10 bg-black/20 px-4 text-sm outline-none placeholder:text-white/25 focus:border-white/20" /><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="City (optional)" className="h-12 rounded-xl border border-white/10 bg-black/20 px-4 text-sm outline-none placeholder:text-white/25 focus:border-white/20" /><VantageSelect value={country} onChange={setCountry} options={countryOptions} ariaLabel="Country" /><button type="submit" disabled={searching || !title.trim()} className="h-12 rounded-xl bg-white px-6 text-sm font-semibold text-black disabled:cursor-not-allowed disabled:opacity-40">{searching ? "Searching…" : "Search live"}</button></div><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-white/40"><label className="flex items-center gap-2"><input type="checkbox" checked={remote} onChange={(event) => setRemote(event.target.checked)} /> Remote only</label><label className="flex items-center gap-2"><input type="checkbox" checked={directOnly} onChange={(event) => setDirectOnly(event.target.checked)} /> Direct employer only</label><label className="flex items-center gap-2">Posted <VantageSelect value={days} onChange={setDays} options={postedOptions} ariaLabel="Posted within" className="w-[116px]" /></label></div></form>
    {(searching || researching) && <section className="vantage-live-panel mt-5 rounded-[24px] border border-white/10 bg-white/[.025] p-5"><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="vantage-research-loader" aria-hidden="true" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><div className="text-sm font-medium">Vantage Live Intelligence</div><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] uppercase tracking-[.16em] text-white/35">{searching ? "Live discovery" : "Deep research"}</span></div><p className="mt-1 text-xs leading-5 text-white/40">{searching ? "Results appear as each live source completes. You do not need to wait for the whole search." : "The live search is complete. Vantage is resolving employer evidence, application paths, and public contacts while you browse."}</p><div className="vantage-research-feed mt-2" /></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{providerStates.map((state) => <div key={state.provider} className="rounded-xl border border-white/[.07] bg-black/15 px-3 py-2.5"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-white/45">{state.provider}</span><span className={`h-1.5 w-1.5 rounded-full ${state.status === "complete" ? "bg-emerald-300" : state.status === "failed" ? "bg-red-300" : "bg-white/30 animate-pulse"}`} /></div><div className="mt-1 text-[11px] text-white/30">{state.status === "searching" ? "Querying live source…" : state.status === "researching" ? "Resolving employer + application path…" : state.status === "queued" ? "Waiting" : state.status === "failed" ? (state.errorMessage ?? "Source unavailable") : `${state.count}${state.totalCount != null ? ` / ${state.totalCount}` : ""} opportunities received`}</div></div>)}</div></section>}
    {error && <div className="mt-5 rounded-2xl border border-red-300/10 bg-red-300/[.03] p-4 text-sm text-red-100/60">{error}</div>}
    {jobs.length > 0 && <section className="mt-7"><div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="section-label">Live opportunities</div><h2 className="mt-1 text-xl font-medium">{visibleJobs.length} matching opportunities</h2><div className="mt-1 text-xs text-white/30">{discoveredCount} discovered · {sourceCount} employer sources · {applicationCount} application paths · {contactCount} public contacts</div></div><div className="flex flex-wrap gap-2 text-[10px] text-white/35">{providerStates.map((state) => <span key={state.provider} className="rounded-full border border-white/10 px-2.5 py-1">{state.provider} · {state.count}{state.totalCount != null ? ` / ${state.totalCount}` : ""}</span>)}</div></div>{enrichment.status !== "idle" && <div className="mb-5 rounded-2xl border border-white/[.08] bg-white/[.018] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/30">Evidence pipeline</div><div className="mt-1 text-sm text-white/60">{enrichment.status === "complete" ? "Deep research complete" : enrichment.status === "partial" ? "Research partially completed" : "Deep research continues while you browse"}</div></div><div className="text-xs text-white/35">{enrichment.aiAnalyzed} AI analysed · {enrichment.evidenceReady} evidence ready</div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-white/50 transition-all" style={{ width: `${enrichment.total ? Math.min(100, Math.round((enrichment.processed / enrichment.total) * 100)) : 0}%` }} /></div><div className="mt-2 text-[11px] text-white/25">{enrichment.processed}/{enrichment.total} listings deeply researched</div></div>}<div className="space-y-4">{pageJobs.map((job) => <JobCard key={job.id} job={job} researching={researching || enrichment.status === "running"} fresh={newIds.has(job.id)} />)}</div><div className="mt-7 flex items-center justify-center gap-2"><button type="button" disabled={resultPage <= 1} onClick={() => setResultPage((page) => Math.max(1, page - 1))} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs text-white/50 disabled:opacity-25">Previous</button><span className="px-3 text-xs text-white/25">Page {resultPage} of {resultPages}</span><button type="button" disabled={resultPage >= resultPages && !Object.values(pagination).some((item) => item.hasMore)} onClick={loadMore} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs text-white/60 disabled:opacity-25">{resultPage < resultPages ? "Next" : "Load more live"}</button></div></section>}
    {!jobs.length && !searching && !error && <div className="mt-16 rounded-[24px] border border-dashed border-white/10 p-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-white/10 bg-white/[.025] text-sm font-black text-white/40">V</div><h2 className="mt-5 text-lg font-medium">Search the live job market</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/35">Vantage will show opportunities as providers return them, then continue resolving employer evidence in the background.</p></div>}
    {researching && <div className="fixed bottom-5 left-1/2 z-40 w-[min(92vw,680px)] -translate-x-1/2 rounded-2xl border border-white/10 bg-[#101116]/95 px-4 py-3 shadow-[0_20px_70px_rgba(0,0,0,.45)] backdrop-blur-xl"><div className="flex items-center gap-3"><div className="vantage-research-loader !h-9 !w-9"><span className="sr-only">Vantage is researching</span></div><div className="min-w-0 flex-1"><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/35">Vantage research</div><div className="mt-1 truncate text-xs text-white/55">{sourceCount} employer sources · {applicationCount} application paths · {contactCount} public contacts found</div></div><div className="hidden text-[10px] text-white/25 sm:block">You can keep reading.</div></div></div>}
  </main>;
}
