import type { JobContactEvidence, JobVerificationStatus, NormalizedJob } from "@/providers/jobs/types";
import { verifyEmployer, type JobVerification } from "@/providers/jobs/verification";

const ATS = ["greenhouse.io", "lever.co", "ashbyhq.com", "smartrecruiters.com", "recruitee.com", "bamboohr.com", "personio.de", "personio.com", "workday.com", "myworkdayjobs.com", "icims.com", "jobvite.com", "teamtailor.com", "workable.com"];
const BLOCKED = ["adzuna.com", "indeed.com", "linkedin.com", "glassdoor.com", "ziprecruiter.com", "monster.com", "jooble.org", "simplyhired.com", "talent.com", "careerbuilder.com", "jobrapido.com"];
function host(value?: string) { try { return value ? new URL(value).hostname.toLowerCase().replace(/^www\./, "") : undefined; } catch { return undefined; } }
function clean(value: unknown) { try { const url = new URL(String(value)); if (!["http:", "https:"].includes(url.protocol)) return undefined; const h = url.hostname.toLowerCase(); if (h === "localhost" || h.endsWith(".local") || /^127\.|^10\.|^192\.168\.|^169\.254\./.test(h)) return undefined; return url.toString(); } catch { return undefined; } }
function isBlocked(value?: string) { const h = host(value) ?? ""; return BLOCKED.some((x) => h === x || h.endsWith(`.${x}`)); }
function isAts(value?: string) { const h = host(value) ?? ""; return ATS.some((x) => h === x || h.endsWith(`.${x}`)); }
function norm(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim(); }
function tokens(value: string) { return norm(value).split(" ").filter((x) => x.length > 2 && !["the", "and", "group", "company", "limited", "ltd", "inc", "corp", "corporation", "llc", "holdings", "services"].includes(x)); }
function companyInText(job: NormalizedJob, text: string) { const source = norm(text); const exact = source.includes(norm(job.companyName)); const parts = tokens(job.companyName); const hits = parts.filter((part) => source.includes(part)).length; return exact || (parts.length > 0 && hits >= Math.min(2, parts.length)); }
function titleInText(job: NormalizedJob, text: string) { const source = norm(text); const exact = source.includes(norm(job.title)); const parts = tokens(job.title); const hits = parts.filter((part) => source.includes(part)).length; return exact || (parts.length > 0 && hits >= Math.max(2, Math.ceil(parts.length * 0.6))); }
function employerHost(job: NormalizedJob, url?: string) { const h = host(url); if (!h || isAts(url) || isBlocked(url)) return false; if (job.companyDomain && (h === job.companyDomain || h.endsWith(`.${job.companyDomain}`))) return true; const compact = norm(job.companyName).replace(/ /g, ""); return Boolean(compact && h.replace(/[^a-z0-9]/g, "").includes(compact)); }
function linksFrom(html: string, base: string) { const result = new Set<string>(); const pattern = /<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi; let match: RegExpExecArray | null; while ((match = pattern.exec(html)) !== null) { const label = norm(match[2] ?? ""); const href = match[1] ?? ""; if (!/(apply|application|career|careers|job|jobs|vacanc|opening|opportunit)/i.test(`${label} ${href}`)) continue; const url = clean(new URL(href, base).toString()); if (url && !isBlocked(url)) result.add(url); } return Array.from(result); }
function contactEvidence(content: string, url: string, job: NormalizedJob) { if (!employerHost(job, url)) return { evidence: [] as JobContactEvidence[] }; const evidence: JobContactEvidence[] = []; const pageHost = host(url); const emails = new Set((content.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi) ?? []).map((x) => x.toLowerCase())); for (const email of emails) { const d = email.split("@")[1] ?? ""; if (pageHost && (d === pageHost || d.endsWith(`.${pageHost}`))) evidence.push({ value: email, url, reason: "Public employer-domain email published on the employer website." }); } const phones = new Set((content.match(/(?:\+?\d[\d\s().-]{6,}\d)/g) ?? []).map((x) => x.replace(/\s+/g, " ").trim())); for (const phone of phones) { const digits = phone.replace(/\D/g, ""); if (digits.length >= 7 && digits.length <= 15) evidence.push({ value: phone, url, reason: "Public phone number published on the employer website." }); } return { phone: evidence.find((x) => /phone/i.test(x.reason))?.value, email: evidence.find((x) => /email/i.test(x.reason))?.value, evidence: evidence.slice(0, 10) }; }
async function firecrawlSearch(query: string): Promise<Array<{ url: string; title: string; description?: string }>> { const key = process.env.FIRECRAWL_API_KEY?.trim(); if (!key) return []; try { const response = await fetch("https://api.firecrawl.dev/v2/search", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ query, limit: 10, scrapeOptions: { formats: ["markdown", "html", "links"], onlyMainContent: true } }), cache: "no-store", signal: AbortSignal.timeout(Number(process.env.FIRECRAWL_SEARCH_TIMEOUT_MS) || 45_000) }); if (!response.ok) return []; const body = await response.json().catch(() => null) as any; const rows = Array.isArray(body?.data) ? body.data : Array.isArray(body?.results) ? body.results : []; return rows.flatMap((row: any) => { const url = clean(row?.url ?? row?.metadata?.sourceURL); if (!url || isBlocked(url)) return []; return [{ url, title: String(row?.title ?? row?.metadata?.title ?? ""), description: typeof row?.description === "string" ? row.description : typeof row?.markdown === "string" ? row.markdown.slice(0, 1200) : undefined }]; }); } catch { return []; } }
async function scrape(url: string) { const key = process.env.FIRECRAWL_API_KEY?.trim(); if (!key || !clean(url) || isBlocked(url)) return undefined; try { const response = await fetch("https://api.firecrawl.dev/v2/scrape", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ url, formats: ["markdown", "html", "links"], onlyMainContent: true, timeout: Number(process.env.FIRECRAWL_TIMEOUT_MS) || 60_000 }), cache: "no-store", signal: AbortSignal.timeout(Number(process.env.FIRECRAWL_TIMEOUT_MS) || 60_000) }); if (!response.ok) return undefined; const body = await response.json().catch(() => null) as any; return body?.success ? body.data : undefined; } catch { return undefined; } }

type ResolverVerification = JobVerification;
function initialVerification(job: NormalizedJob): ResolverVerification { return { status: job.verificationStatus === "stale" ? "unverified" : job.verificationStatus, score: job.verificationScore ?? 0, reasons: [...job.verificationReasons], evidence: job.verificationEvidence ? [...job.verificationEvidence] : [], ...(job.companyDomain ? { companyDomain: job.companyDomain } : {}) }; }

export async function resolveApplicationAndContacts(job: NormalizedJob): Promise<NormalizedJob> {
  const location = [job.city, job.location, job.countryCode].filter(Boolean).join(" ");
  const queries = [`"${job.companyName}" "${job.title}" apply careers ${location}`, `"${job.companyName}" "${job.title}" application ${location}`, `"${job.companyName}" "${job.title}" jobs ${location}`, `"${job.companyName}" contact phone ${location}`, `"${job.companyName}" contact email ${location}`];
  const discovered = (await Promise.all(queries.map(firecrawlSearch))).flat();
  const unique = Array.from(new Map(discovered.map((item) => [item.url, item])).values());
  const applicationSeeds = unique.filter((item) => titleInText(job, `${item.title} ${item.description ?? ""}`) && (companyInText(job, `${item.title} ${item.description ?? ""}`) || employerHost(job, item.url) || isAts(item.url))).sort((a, b) => ((isAts(b.url) ? 20 : 0) + (employerHost(job, b.url) ? 25 : 0)) - ((isAts(a.url) ? 20 : 0) + (employerHost(job, a.url) ? 25 : 0))).slice(0, 10);
  const seeds = Array.from(new Set([job.companyWebsite, job.applyUrl, ...applicationSeeds.map((x) => x.url), ...unique.filter((x) => employerHost(job, x.url)).map((x) => x.url)].filter(Boolean) as string[])).slice(0, 12);
  const pages: Array<{ url: string; content: string; links: string[] }> = [];
  for (const url of seeds) { const data = await scrape(url); if (!data) continue; const actualUrl = clean(data.metadata?.sourceURL ?? url) ?? url; const html = typeof data.html === "string" ? data.html : ""; const markdown = typeof data.markdown === "string" ? data.markdown : ""; pages.push({ url: actualUrl, content: `${markdown}\n${html}`, links: Array.from(new Set([...(Array.isArray(data.links) ? data.links : []), ...linksFrom(html, actualUrl)].map(clean).filter(Boolean) as string[])) }); }
  const secondLevel = Array.from(new Set(pages.flatMap((page) => page.links).filter((url) => /apply|application|career|careers|job|jobs|vacanc|opening/i.test(url)))).slice(0, 16);
  for (const url of secondLevel) { if (pages.some((page) => page.url === url)) continue; const data = await scrape(url); if (!data) continue; const actualUrl = clean(data.metadata?.sourceURL ?? url) ?? url; const html = typeof data.html === "string" ? data.html : ""; const markdown = typeof data.markdown === "string" ? data.markdown : ""; pages.push({ url: actualUrl, content: `${markdown}\n${html}`, links: Array.from(new Set([...(Array.isArray(data.links) ? data.links : []), ...linksFrom(html, actualUrl)].map(clean).filter(Boolean) as string[])) }); }
  const applicationCandidates = pages.flatMap((page) => [page.url, ...page.links].filter((url) => (employerHost(job, url) || isAts(url)) && !isBlocked(url)).map((url) => ({ url, page, score: (titleInText(job, page.content) ? 50 : 0) + (companyInText(job, page.content) ? 30 : 0) + (/apply|application/i.test(url) ? 25 : 0) + (/career|jobs?|vacanc|opening/i.test(url) ? 15 : 0) + (isAts(url) ? 15 : 0) + (employerHost(job, url) ? 15 : 0) })).filter((item) => item.score >= 70 && titleInText(job, item.page.content))).sort((a, b) => b.score - a.score);
  const applyUrl = applicationCandidates[0]?.url;
  let companyWebsite = job.companyWebsite; const employerPage = pages.find((page) => employerHost(job, page.url)); if (!companyWebsite && employerPage) companyWebsite = employerPage.url;
  let phone = job.companyPhone; let email = job.companyEmail; let contactUrl = job.companyContactUrl; const contacts: JobContactEvidence[] = [...(job.companyContactEvidence ?? [])];
  for (const page of pages) { const found = contactEvidence(page.content, page.url, job); if (!phone && found.phone) phone = found.phone; if (!email && found.email) email = found.email; contacts.push(...found.evidence); if (!contactUrl && /contact/i.test(page.url) && employerHost(job, page.url)) contactUrl = page.url; }
  let verification: ResolverVerification = initialVerification(job);
  try { verification = await verifyEmployer({ ...job, companyWebsite, companyDomain: host(companyWebsite) ?? job.companyDomain, applyUrl, sourceUrl: job.sourceUrl }); } catch { /* preserve prior verification */ }
  const reasons = [...verification.reasons]; if (!applyUrl) reasons.push("Vantage searched employer and ATS sources and did not find a public application page tied to this exact role."); if (!phone && !email) reasons.push("Vantage searched public employer contact pages and did not find a public employer phone or email.");
  return { ...job, companyWebsite, companyDomain: verification.companyDomain ?? host(companyWebsite) ?? job.companyDomain, applyUrl, sourceUrl: applyUrl ?? job.sourceUrl, companyPhone: phone, companyEmail: email, companyContactUrl: contactUrl, companyContactEvidence: Array.from(new Map(contacts.map((item) => [`${item.value}|${item.url}`, item])).values()).slice(0, 12), verificationStatus: verification.status as JobVerificationStatus, verificationScore: verification.score, verificationReasons: reasons, verificationEvidence: verification.evidence };
}

export async function resolveApplicationAndContactsBatch(jobs: NormalizedJob[], concurrency = 2) { const output = [...jobs]; const queue = jobs.map((job, index) => ({ job, index })); const workers = Math.min(Math.max(1, concurrency), queue.length || 1); async function worker() { while (queue.length) { const item = queue.shift(); if (!item) return; try { output[item.index] = await resolveApplicationAndContacts(item.job); } catch { output[item.index] = item.job; } } } await Promise.all(Array.from({ length: workers }, () => worker())); return output; }
