import type { JobContactEvidence, NormalizedJob } from "@/providers/jobs/types";
import { searchEvidence } from "@/providers/evidence-search/router";
import { firecrawlWebsiteResearchProvider } from "@/providers/website-research/firecrawl";
import { verifyEmployer } from "@/providers/jobs/verification";

const BLOCKED_HOSTS = new Set(["adzuna.com", "indeed.com", "linkedin.com", "glassdoor.com", "ziprecruiter.com", "monster.com", "jooble.org", "simplyhired.com", "talent.com", "careerbuilder.com", "jobrapido.com"]);
const ATS_HOSTS = ["greenhouse.io", "lever.co", "ashbyhq.com", "smartrecruiters.com", "recruitee.com", "bamboohr.com", "personio.de", "personio.com", "workday.com", "myworkdayjobs.com", "icims.com", "jobvite.com", "teamtailor.com", "workable.com"];
const robotsCache = new Map<string, string[] | null>();

function host(url?: string) { try { return url ? new URL(url).hostname.toLowerCase().replace(/^www\./, "") : undefined; } catch { return undefined; } }
function safeUrl(value?: string) { try { const url = new URL(value ?? ""); if (!["http:", "https:"].includes(url.protocol)) return undefined; const h = url.hostname.toLowerCase(); if (h === "localhost" || h.endsWith(".local") || /^127\.|^10\.|^192\.168\.|^169\.254\./.test(h) || /^::1$|^fc|^fd/i.test(h)) return undefined; return url.toString(); } catch { return undefined; } }
function stripHtml(value: string) { return value.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<noscript[\s\S]*?<\/noscript>/gi, " ").replace(/<[^>]+>/g, " ").replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/&#39;|&apos;/gi, "'").replace(/&quot;/gi, '"').replace(/&#x2F;/gi, "/").replace(/\s+/g, " ").trim(); }
function normalizeText(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim(); }
function companyTokens(name: string) { return normalizeText(name).split(" ").filter((x) => x.length > 2 && !["the", "and", "group", "company", "limited", "ltd", "inc", "corp", "corporation", "llc", "holdings", "services"].includes(x)); }
function isAtsHost(value?: string) { const h = host(value) ?? ""; return ATS_HOSTS.some((ats) => h === ats || h.endsWith(`.${ats}`)); }
function isBlockedHost(url?: string) { const h = host(url) ?? ""; return BLOCKED_HOSTS.has(h) || Array.from(BLOCKED_HOSTS).some((blocked) => h.endsWith(`.${blocked}`)); }
function companyHostMatch(name: string, url?: string) { const h = host(url) ?? ""; if (!h || isAtsHost(h)) return false; const compactName = normalizeText(name).replace(/ /g, ""); const compactHost = h.replace(/[^a-z0-9]/g, ""); if (compactName && compactHost.includes(compactName)) return true; const text = h.replace(/[^a-z0-9]+/g, " "); const tokens = companyTokens(name); return tokens.length > 0 && tokens.filter((token) => text.includes(token)).length >= Math.min(2, tokens.length); }
function sameHost(left?: string, right?: string) { const a = host(left); const b = host(right); return Boolean(a && b && (a === b || a.endsWith(`.${b}`) || b.endsWith(`.${a}`))); }
function trustedApplication(job: NormalizedJob, url?: string) { if (!url || isBlockedHost(url)) return undefined; return (companyHostMatch(job.companyName, url) || isAtsHost(url) || sameHost(url, job.companyWebsite)) ? url : undefined; }

async function robotsRules(targetUrl: string) { const targetHost = host(targetUrl); if (!targetHost) return null; if (robotsCache.has(targetHost)) return robotsCache.get(targetHost) ?? null; try { const response = await fetch(`https://${targetHost}/robots.txt`, { cache: "no-store", signal: AbortSignal.timeout(5_000), headers: { Accept: "text/plain" } }); if (!response.ok) { robotsCache.set(targetHost, null); return null; } const text = await response.text(); const rules: string[] = []; let applies = false; for (const rawLine of text.split(/\r?\n/)) { const line = rawLine.split("#", 1)[0].trim(); if (!line) continue; const [keyRaw, valueRaw] = line.split(":", 2); const key = keyRaw?.trim().toLowerCase(); const value = valueRaw?.trim() ?? ""; if (key === "user-agent") applies = value === "*"; else if (key === "disallow" && applies && value) rules.push(value); } robotsCache.set(targetHost, rules); return rules; } catch { robotsCache.set(targetHost, null); return null; } }
async function robotsAllowed(targetUrl: string) { const rules = await robotsRules(targetUrl); if (!rules?.length) return true; try { const url = new URL(targetUrl); return !rules.some((rule) => rule === "/" || url.pathname.startsWith(rule)); } catch { return false; } }

interface PublicPage { html: string; url: string; }
async function fetchPublic(url: string): Promise<PublicPage | undefined> { const safe = safeUrl(url); if (!safe || isBlockedHost(safe) || !(await robotsAllowed(safe))) return undefined; try { const response = await fetch(safe, { headers: { Accept: "text/html,application/xhtml+xml" }, cache: "no-store", redirect: "follow", signal: AbortSignal.timeout(10_000) }); if (!response.ok) return undefined; const type = response.headers.get("content-type") ?? ""; if (!/text\/html|application\/xhtml\+xml/i.test(type)) return undefined; return { html: (await response.text()).slice(0, 600_000), url: safeUrl(response.url) ?? safe }; } catch { return undefined; } }
function extractDescription(html: string) { const main = html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1] ?? html.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1] ?? html; return stripHtml(main).slice(0, 40_000); }
function roleMatch(text: string, job: NormalizedJob) { const lower = text.toLowerCase(); if (lower.includes(job.title.toLowerCase())) return true; const tokens = normalizeText(job.title).split(" ").filter((token) => token.length > 2); const hits = tokens.filter((token) => lower.includes(token)).length; return tokens.length > 0 && hits >= Math.max(2, Math.ceil(tokens.length * 0.6)); }
function pageCompanyMatch(text: string, job: NormalizedJob, url: string) { if (companyHostMatch(job.companyName, url)) return true; const lower = text.toLowerCase(); if (lower.includes(job.companyName.toLowerCase())) return true; const tokens = companyTokens(job.companyName); return tokens.length > 0 && tokens.filter((token) => lower.includes(token)).length >= Math.min(2, tokens.length); }

function pageLinks(html: string, baseUrl: string, job: NormalizedJob) { const result: Array<{ url: string; score: number; label: string }> = []; const pattern = /<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi; let match: RegExpExecArray | null; const titleTokens = normalizeText(job.title).split(" ").filter((token) => token.length > 2); while ((match = pattern.exec(html)) !== null) { const href = match[1] ?? ""; const label = stripHtml(match[2] ?? ""); if (!/(apply|job|career|careers|vacanc|opening|opportunit)/i.test(`${label} ${href}`)) continue; const url = safeUrl(new URL(href, baseUrl).toString()); if (!url || isBlockedHost(url)) continue; const lower = `${label} ${href}`.toLowerCase(); let score = 0; if (/\bapply(?: now| here)?\b/i.test(label)) score += 10; if (/\b(job|opening|vacanc|opportunit)\b/i.test(lower)) score += 5; score += titleTokens.filter((token) => normalizeText(`${label} ${href}`).includes(token)).length * 2; if (isAtsHost(url)) score += 3; result.push({ url, score, label }); } return Array.from(new Map(result.map((item) => [item.url, item])).values()).sort((a, b) => b.score - a.score).slice(0, 12); }
function supportingLinks(html: string, baseUrl: string) { const result: Array<{ url: string; score: number; label: string }> = []; const pattern = /<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi; let match: RegExpExecArray | null; while ((match = pattern.exec(html)) !== null) { const href = match[1] ?? ""; const label = stripHtml(match[2] ?? ""); if (!/(contact|about|team|people|career|careers|jobs|vacanc|opening|opportunit)/i.test(`${label} ${href}`)) continue; const url = safeUrl(new URL(href, baseUrl).toString()); if (!url || isBlockedHost(url) || isAtsHost(url)) continue; let score = 0; if (/contact/i.test(`${label} ${href}`)) score += 10; if (/career|jobs?|vacanc|opening/i.test(`${label} ${href}`)) score += 5; if (/about|team|people/i.test(`${label} ${href}`)) score += 2; result.push({ url, score, label }); } return Array.from(new Map(result.map((item) => [item.url, item])).values()).sort((a, b) => b.score - a.score).slice(0, 10); }

function extractContacts(html: string, pageUrl: string, job: NormalizedJob): { phone?: string; email?: string; contactUrl?: string; evidence: JobContactEvidence[] } { if (!companyHostMatch(job.companyName, pageUrl)) return { evidence: [] }; const pageHost = host(pageUrl); if (!pageHost) return { evidence: [] }; const evidence: JobContactEvidence[] = []; const emails = new Set<string>(); const phones = new Set<string>(); const mailtoPattern = /href=["']mailto:([^"'? >]+)/gi; let mailMatch: RegExpExecArray | null; while ((mailMatch = mailtoPattern.exec(html)) !== null) emails.add(mailMatch[1].trim().toLowerCase()); const textContent = stripHtml(html); const emailPattern = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi; let emailMatch: RegExpExecArray | null; while ((emailMatch = emailPattern.exec(textContent)) !== null) emails.add(emailMatch[0].toLowerCase()); for (const email of emails) { const emailDomain = email.split("@")[1] ?? ""; if (emailDomain === pageHost || emailDomain.endsWith(`.${pageHost}`)) evidence.push({ value: email, url: pageUrl, reason: "Public employer-domain email published on the employer website." }); } const telPattern = /href=["']tel:([^"']+)["']/gi; let telMatch: RegExpExecArray | null; while ((telMatch = telPattern.exec(html)) !== null) phones.add(telMatch[1].replace(/[^\d+]/g, "")); const phonePattern = /(?:\+?\d[\d\s().-]{6,}\d)/g; let phoneMatch: RegExpExecArray | null; while ((phoneMatch = phonePattern.exec(textContent)) !== null) phones.add(phoneMatch[0].replace(/\s+/g, " ").trim()); for (const phone of phones) { const digits = phone.replace(/\D/g, ""); if (digits.length >= 7 && digits.length <= 15) evidence.push({ value: phone, url: pageUrl, reason: "Public phone number published on the employer website." }); } const contactUrl = supportingLinks(html, pageUrl).find((item) => /contact/i.test(`${item.label} ${item.url}`))?.url; return { phone: evidence.find((item) => /phone/i.test(item.reason))?.value, email: evidence.find((item) => /email/i.test(item.reason))?.value, contactUrl, evidence: evidence.slice(0, 10) }; }

async function firecrawlEvidence(job: NormalizedJob, url?: string) { if (!url || !process.env.FIRECRAWL_API_KEY?.trim() || isBlockedHost(url)) return false; try { const result = await firecrawlWebsiteResearchProvider.research({ businessId: job.id, url, maxPages: Math.min(Math.max(Number(process.env.JOB_FIRECRAWL_MAX_PAGES) || 5, 1), 5) }); return result.pagesFetched.length > 0 && result.evidence.length > 0; } catch { return false; } }

function scoreEmployerResult(job: NormalizedJob, item: { title: string; url: string; snippet?: string }) { if (isBlockedHost(item.url) || isAtsHost(item.url)) return 0; const text = normalizeText(`${item.title} ${item.snippet ?? ""}`); const name = normalizeText(job.companyName); const tokens = companyTokens(job.companyName); const exact = text.includes(name); const hits = tokens.filter((token) => text.includes(token)).length; const hostMatch = companyHostMatch(job.companyName, item.url); if (!exact && !hostMatch && hits < Math.min(2, tokens.length)) return 0; return (exact ? 15 : 0) + (hostMatch ? 18 : 0) + hits * 4 + (/\b(official|careers?|jobs?|contact)\b/i.test(text) ? 5 : 0); }
function scoreJobResult(job: NormalizedJob, item: { title: string; url: string; snippet?: string }) { if (isBlockedHost(item.url)) return 0; const text = `${item.title} ${item.snippet ?? ""}`.toLowerCase(); const tokens = companyTokens(job.companyName); const exactCompany = text.includes(job.companyName.toLowerCase()); const companyHits = tokens.filter((token) => text.includes(token)).length; const exactTitle = text.includes(job.title.toLowerCase()); const titleTokens = normalizeText(job.title).split(" ").filter((token) => token.length > 2); const titleHits = titleTokens.filter((token) => text.includes(token)).length; if (!exactCompany && companyHits < Math.min(2, tokens.length)) return 0; if (!exactTitle && titleHits < Math.max(2, Math.ceil(titleTokens.length * 0.5))) return 0; let score = (exactCompany ? 14 : companyHits * 3) + (exactTitle ? 16 : titleHits * 2) + (/\b(apply|careers?|jobs?|vacanc|opening)\b/i.test(text) ? 6 : 0); if (isAtsHost(item.url)) score += 8; if (companyHostMatch(job.companyName, item.url)) score += 18; return score; }

async function searchEmployerCandidates(job: NormalizedJob, location: string) { const queries = [`"${job.companyName}" official website`, `"${job.companyName}" careers ${location}`, `"${job.companyName}" contact phone email`]; const all: Array<{ title: string; url: string; snippet?: string }> = []; for (const query of queries) { try { const search = await searchEvidence({ businessName: job.companyName, location, country: job.countryCode, category: "company", limit: 10, query }, "both"); all.push(...search.results.flatMap((result) => result.results)); } catch { /* keep other sources */ } } return all.map((item) => ({ item, score: scoreEmployerResult(job, item) })).filter((candidate) => candidate.score > 0).sort((a, b) => b.score - a.score).slice(0, 8); }
async function searchJobCandidates(job: NormalizedJob, location: string) { const domainHint = job.companyWebsite ? ` site:${host(job.companyWebsite)}` : ""; const queries = [`"${job.companyName}" "${job.title}" ${location} official careers apply`, `"${job.companyName}" "${job.title}" ${location} application`, `"${job.companyName}" "${job.title}" careers${domainHint}`, `"${job.companyName}" "${job.title}" contact phone email`]; const all: Array<{ title: string; url: string; snippet?: string }> = []; for (const query of queries) { try { const search = await searchEvidence({ businessName: job.companyName, location, country: job.countryCode, category: "employment", limit: 10, query }, "both"); all.push(...search.results.flatMap((result) => result.results)); } catch { /* preserve other search paths */ } const ranked = all.map((item) => ({ item, score: scoreJobResult(job, item) })).filter((candidate) => candidate.score > 0).sort((a, b) => b.score - a.score); if (ranked.length >= 5) return ranked.slice(0, 10); } return all.map((item) => ({ item, score: scoreJobResult(job, item) })).filter((candidate) => candidate.score > 0).sort((a, b) => b.score - a.score).slice(0, 10); }

async function enrichFromPage(best: NormalizedJob, url: string, mode: "employer" | "job", candidateScore = 0) { const page = await fetchPublic(url); if (!page) return best; const pageText = extractDescription(page.html); const companyConfirmed = pageCompanyMatch(pageText, best, page.url); const titleConfirmed = roleMatch(pageText, best); const atsPage = isAtsHost(page.url); if (mode === "employer" && !companyConfirmed) return best; if (mode === "job" && (!titleConfirmed || (!companyConfirmed && !(atsPage && candidateScore >= 25)))) return best;
  const applicationCandidates = pageLinks(page.html, page.url, best); const existingEmployer = best.companyWebsite && !isAtsHost(best.companyWebsite) ? best.companyWebsite : undefined; const discoveredEmployer = !atsPage && companyConfirmed && companyHostMatch(best.companyName, page.url) ? page.url : undefined; const employerWebsite = existingEmployer ?? discoveredEmployer; const application = atsPage ? page.url : applicationCandidates.find((candidate) => { const candidateHost = host(candidate.url); const employerHost = host(employerWebsite); return Boolean(candidateHost && ((employerHost && (candidateHost === employerHost || candidateHost.endsWith(`.${employerHost}`))) || isAtsHost(candidate.url)) && /\bapply\b|\b(job|opening|vacanc|opportunit)\b/i.test(`${candidate.label} ${candidate.url}`)); })?.url;
  const contacts = employerWebsite && companyHostMatch(best.companyName, page.url) ? extractContacts(page.html, page.url, best) : { evidence: [] as JobContactEvidence[] };
  const firecrawled = await firecrawlEvidence(best, page.url);
  const trustedExistingApply = trustedApplication({ ...best, companyWebsite: employerWebsite }, best.applyUrl);
  return { ...best, companyWebsite: employerWebsite ?? best.companyWebsite, companyDomain: host(employerWebsite) ?? best.companyDomain, sourceUrl: mode === "job" ? page.url : best.sourceUrl, applyUrl: trustedApplication({ ...best, companyWebsite: employerWebsite }, application) ?? trustedExistingApply, description: pageText.length > (best.description?.length ?? 0) ? pageText : best.description, companyPhone: contacts.phone ?? best.companyPhone, companyEmail: contacts.email ?? best.companyEmail, companyContactUrl: contacts.contactUrl ?? best.companyContactUrl, companyContactEvidence: contacts.evidence.length ? [...(best.companyContactEvidence ?? []), ...contacts.evidence].slice(0, 12) : best.companyContactEvidence, verificationReasons: [...new Set([...best.verificationReasons, mode === "job" ? "Public job-source research matched the named role." : "Public employer-domain research matched the named company.", ...(employerWebsite && !best.companyWebsite ? ["Vantage resolved a public employer website from independent web evidence."] : []), ...(application ? [atsPage ? "A public ATS job page matching the role was resolved." : "A public employer application path matching the role was resolved."] : []), ...(contacts.evidence.length ? ["Public employer contact details were found on the employer domain."] : []), ...(firecrawled ? ["Firecrawl independently crawled the public source and returned evidence."] : [])])] };
}

async function enrichEmployerContacts(job: NormalizedJob) { if (!job.companyWebsite || !companyHostMatch(job.companyName, job.companyWebsite)) return job; const page = await fetchPublic(job.companyWebsite); if (!page) return job; const links = supportingLinks(page.html, page.url); let best = job; const homeContacts = extractContacts(page.html, page.url, best); if (homeContacts.evidence.length) best = { ...best, companyPhone: homeContacts.phone ?? best.companyPhone, companyEmail: homeContacts.email ?? best.companyEmail, companyContactUrl: homeContacts.contactUrl ?? best.companyContactUrl, companyContactEvidence: [...(best.companyContactEvidence ?? []), ...homeContacts.evidence].slice(0, 12) }; const contactPages = links.filter((item) => /contact/i.test(`${item.label} ${item.url}`)).slice(0, 3); for (const item of contactPages) { const contactPage = await fetchPublic(item.url); if (!contactPage) continue; const contacts = extractContacts(contactPage.html, contactPage.url, best); if (contacts.evidence.length) { best = { ...best, companyPhone: contacts.phone ?? best.companyPhone, companyEmail: contacts.email ?? best.companyEmail, companyContactUrl: contactPage.url, companyContactEvidence: [...(best.companyContactEvidence ?? []), ...contacts.evidence].slice(0, 12) }; if (best.companyPhone || best.companyEmail) break; } } return best; }

export async function researchJobSource(job: NormalizedJob): Promise<NormalizedJob> { const location = job.location ?? [job.city, job.countryCode].filter(Boolean).join(", "); let best = job;
  if (best.companyWebsite && !isAtsHost(best.companyWebsite)) best = await enrichFromPage(best, best.companyWebsite, "employer");
  if (!best.companyWebsite || isAtsHost(best.companyWebsite)) { const employerCandidates = await searchEmployerCandidates(best, location); for (const candidate of employerCandidates) { const url = safeUrl(candidate.item.url); if (!url) continue; const enriched = await enrichFromPage(best, url, "employer", candidate.score); if (enriched !== best && enriched.companyWebsite) { best = enriched; break; } } }
  if (best.companyWebsite) best = await enrichEmployerContacts(best);
  const jobCandidates = await searchJobCandidates(best, location); for (const candidate of jobCandidates) { const url = safeUrl(candidate.item.url); if (!url) continue; const enriched = await enrichFromPage(best, url, "job", candidate.score); if (enriched === best) continue; best = enriched; if (best.applyUrl && best.companyWebsite && (best.companyPhone || best.companyEmail)) break; }
  if (best.companyWebsite) { await firecrawlEvidence(best, best.companyWebsite); }
  if (best.applyUrl && isAtsHost(best.applyUrl)) { await firecrawlEvidence(best, best.applyUrl); }
  try { const verification = await verifyEmployer(best); return { ...best, companyDomain: verification.companyDomain ?? best.companyDomain, verificationStatus: verification.status, verificationScore: verification.score, verificationReasons: verification.reasons, verificationEvidence: [...verification.evidence, ...(best.companyContactEvidence ?? []).map((item) => ({ url: item.url, reason: item.reason }))] }; } catch { return best; }
}

export async function researchJobs(jobs: NormalizedJob[], maxJobs = jobs.length) { const selected = jobs.slice(0, Math.max(0, Math.min(maxJobs, jobs.length))); const results = new Map<string, NormalizedJob>(); const queue = [...selected]; const concurrency = Math.max(1, Math.min(Number(process.env.JOB_SOURCE_RESEARCH_CONCURRENCY) || 3, 5)); async function worker() { while (queue.length) { const job = queue.shift(); if (!job) return; try { results.set(job.id, await researchJobSource(job)); } catch { results.set(job.id, job); } } } await Promise.all(Array.from({ length: Math.min(concurrency, queue.length || 1) }, () => worker())); return jobs.map((job) => results.get(job.id) ?? job); }
