import type { JobProvider, JobProviderResult, JobSearchQuery, NormalizedJob } from "./types";

export type RegionalSourceMode = "feed" | "web";
export type RegionalSource = {
  provider: JobProvider;
  name: string;
  countries: string[];
  mode: RegionalSourceMode[];
  seedUrls: string[];
  feedUrls?: string[];
  notes: string;
};

export const REGIONAL_JOB_SOURCES: RegionalSource[] = [
  { provider: "myjobmag", name: "MyJobMag", countries: ["NG", "GH", "KE", "ZA"], mode: ["feed", "web"], seedUrls: ["https://www.myjobmag.com/"], feedUrls: ["https://www.myjobmag.com/jobsxml.xml", "https://www.myjobmag.com/jobsxml_by_categories.xml", "https://www.myjobmag.com/aggregate_feed.xml"], notes: "Public XML/RSS-style feeds plus public listing pages." },
  { provider: "jobberman", name: "Jobberman", countries: ["NG", "GH"], mode: ["web"], seedUrls: ["https://www.jobberman.com/jobs", "https://www.jobberman.com/"], notes: "Public job pages; no public Jobberman API assumed." },
  { provider: "hotnigerianjobs", name: "Hot Nigerian Jobs", countries: ["NG"], mode: ["web"], seedUrls: ["https://www.hotnigerianjobs.com/"], notes: "Public Nigerian vacancy pages." },
  { provider: "jobgurus", name: "Jobgurus", countries: ["NG"], mode: ["feed", "web"], seedUrls: ["https://www.jobgurus.com.ng/"], notes: "Public job pages; site advertises XML/RSS feeds." },
  { provider: "jobsinnigeria", name: "Jobs In Nigeria", countries: ["NG"], mode: ["web"], seedUrls: ["https://www.jobsinnigeria.ng/"], notes: "Public Nigerian vacancy pages." },
  { provider: "workinnigeria", name: "Work in Nigeria", countries: ["NG"], mode: ["web"], seedUrls: ["https://workinnigeria.org/vacancy/"], notes: "Public vacancy archive." },
  { provider: "fuzu", name: "Fuzu", countries: ["NG", "KE", "UG"], mode: ["web"], seedUrls: ["https://www.fuzu.com/nigeria/job", "https://www.fuzu.com/job"], notes: "Public regional job pages." },
  { provider: "careerjet", name: "Careerjet", countries: ["NG", "GH", "KE", "ZA"], mode: ["web"], seedUrls: ["https://www.careerjet.com.ng/", "https://www.careerjet.co.za/"], notes: "Aggregator used only for discovery/corroboration, never as verification truth." },
  { provider: "brightermonday", name: "BrighterMonday", countries: ["KE", "UG", "GH"], mode: ["web"], seedUrls: ["https://www.brightermonday.co.ke/", "https://www.brightermonday.co.ug/"], notes: "Regional job marketplace; preserve listing provenance." },
  { provider: "careers24", name: "Careers24", countries: ["ZA"], mode: ["web"], seedUrls: ["https://www.careers24.com/jobs"], notes: "South African public jobs surface." },
  { provider: "careerjunction", name: "CareerJunction", countries: ["ZA"], mode: ["web"], seedUrls: ["https://www.careerjunction.co.za/"], notes: "South African public jobs surface." },
  { provider: "pnet", name: "PNet", countries: ["ZA"], mode: ["web"], seedUrls: ["https://www.pnet.co.za/"], notes: "South African public jobs surface." },
];

const TIMEOUT_MS = Number(process.env.JOB_SCRAPER_TIMEOUT_MS) || 10_000;
const MAX_DETAIL_PAGES = Math.max(1, Math.min(Number(process.env.JOB_SCRAPER_DETAIL_PAGES) || 8, 20));

function text(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
function htmlText(value?: string) { return (value ?? "").replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]*>/g, " ").replace(/&#39;|&apos;/gi, "'").replace(/&quot;/gi, '"').replace(/&amp;/gi, "&").replace(/&nbsp;/gi, " ").replace(/\s+/g, " ").trim(); }
function decode(value: string) { return htmlText(value).replace(/<!\[CDATA\[|\]\]>/g, "").trim(); }
function cleanUrl(value?: string, base?: string) { try { const url = new URL(value ?? "", base); if (!["http:", "https:"].includes(url.protocol)) return undefined; url.hash = ""; return url.toString(); } catch { return undefined; } }
function domain(value?: string) { const url = cleanUrl(value); if (!url) return undefined; return new URL(url).hostname.toLowerCase().replace(/^www\./, ""); }
function countryAllowed(source: RegionalSource, query: JobSearchQuery) { const code = (query.countryCode ?? "NG").toUpperCase(); return source.countries.includes(code); }
function titleMatches(title: string, query: string) { const terms = query.toLowerCase().split(/\s+/).filter((t) => t.length > 2); if (!terms.length) return true; const hay = title.toLowerCase(); return terms.some((term) => hay.includes(term)); }
function stableId(provider: JobProvider, url: string, title: string, company: string) { const key = `${provider}|${url}|${title}|${company}`.toLowerCase().replace(/[^a-z0-9|]+/g, "-"); return `${provider}:${key.slice(0, 180)}`; }
function parseJsonLd(html: string): Record<string, unknown>[] { const items: Record<string, unknown>[] = []; const matches = html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi); for (const match of matches) { try { const raw = match[1].trim(); const parsed = JSON.parse(raw) as unknown; const values = Array.isArray(parsed) ? parsed : [parsed]; for (const item of values) if (item && typeof item === "object") items.push(item as Record<string, unknown>); } catch { /* ignore malformed JSON-LD */ } } return items; }
function asLocation(value: unknown) { if (!value) return undefined; const list = Array.isArray(value) ? value : [value]; return list.map((entry: any) => [entry?.address?.addressLocality, entry?.address?.addressRegion, entry?.address?.addressCountry, entry?.name].filter(Boolean).join(", ")).filter(Boolean).join(" | ") || (typeof value === "string" ? value : undefined); }
function parseJobPostingJsonLd(item: Record<string, unknown>, provider: JobProvider, sourceName: string, sourceUrl: string): NormalizedJob | null { const typeValue = item["@type"]; const isJob = typeValue === "JobPosting" || (Array.isArray(typeValue) && typeValue.includes("JobPosting")); if (!isJob) return null; const title = text(item.title); const org = item.hiringOrganization as Record<string, unknown> | undefined; const companyName = text(org?.name) ?? text(item.hiringOrganization); if (!title || !companyName) return null; const hiringUrl = cleanUrl(text(org?.sameAs) ?? text(org?.url), sourceUrl); const application = cleanUrl(text(item.url), sourceUrl); const identifier = text((item.identifier as any)?.value) ?? application ?? sourceUrl; const jobLocation = asLocation(item.jobLocation); const addressCountry = Array.isArray(item.jobLocation) ? undefined : text((item.jobLocation as any)?.address?.addressCountry); const baseReasons = [`Collected from ${sourceName}'s public source surface; employer verification is performed independently by Vantage.`]; if (hiringUrl) baseReasons.push("Public structured data exposed an employer URL for independent ownership checks."); return { id: stableId(provider, identifier, title, companyName), provider, title, companyName, companyDomain: domain(hiringUrl), companyWebsite: hiringUrl, description: htmlText(text(item.description)), location: jobLocation, countryCode: addressCountry?.length === 2 ? addressCountry.toUpperCase() : undefined, employmentType: text(item.employmentType), remote: /telecommute|remote/i.test(JSON.stringify(item.jobLocationType ?? item.jobLocation ?? "")) ? true : undefined, postedAt: text(item.datePosted), applyUrl: application, sourceUrl, sourceName, requirements: [], verificationStatus: "unverified", verificationReasons: baseReasons } satisfies NormalizedJob; }
function parseFeed(xml: string, source: RegionalSource): NormalizedJob[] { const jobs: NormalizedJob[] = []; const itemMatches = xml.matchAll(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi); for (const itemMatch of itemMatches) { const item = itemMatch[0]; const title = decode((item.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] ?? "").trim()); const linkTag = item.match(/<link[^>]*(?:href=["']([^"']+)["'][^>]*)?(?:>([^<]+)<)?\/link>/i); const link = cleanUrl(linkTag?.[1] ?? linkTag?.[2], source.feedUrls?.[0]); const description = decode(item.match(/<(?:description|summary|content:encoded)[^>]*>([\s\S]*?)<\/(?:description|summary|content:encoded)>/i)?.[1] ?? ""); const pub = decode(item.match(/<(?:pubDate|published|updated)[^>]*>([\s\S]*?)<\/(?:pubDate|published|updated)>/i)?.[1] ?? ""); const creator = decode(item.match(/<(?:dc:creator|author)[^>]*>([\s\S]*?)<\/(?:dc:creator|author)>/i)?.[1] ?? ""); if (!title || !link) continue; jobs.push({ id: stableId(source.provider, link, title, creator || "unknown"), provider: source.provider, title, companyName: creator || "Unknown employer", description, sourceUrl: link, sourceName: source.name, postedAt: pub ? new Date(pub).toISOString() : undefined, requirements: [], verificationStatus: "unverified", verificationReasons: [`Collected from ${source.name} public feed; employer identity and application path are verified separately by Vantage.`] }); } return jobs; }
async function fetchText(url: string) { const response = await fetch(url, { cache: "no-store", headers: { Accept: "text/html,application/xhtml+xml,application/xml,application/rss+xml,text/xml;q=0.9,*/*;q=0.5", "User-Agent": "VantageJobsBot/1.0 (+https://vantage.example/jobs)" }, signal: AbortSignal.timeout(TIMEOUT_MS) }); const body = await response.text(); if (!response.ok) throw new Error(`HTTP_${response.status}`); return body; }
function extractCandidateLinks(html: string, baseUrl: string, query: JobSearchQuery) { const links = new Set<string>(); const matches = html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi); for (const match of matches) { const href = cleanUrl(match[1], baseUrl); const anchorText = htmlText(match[2]); if (!href || !anchorText || anchorText.length < 5 || !titleMatches(anchorText, query.title)) continue; const lower = href.toLowerCase(); if (/login|signup|register|privacy|terms|contact|about|facebook|twitter|instagram|linkedin/.test(lower)) continue; links.add(href); if (links.size >= MAX_DETAIL_PAGES) break; } return Array.from(links); }
async function scrapeSource(source: RegionalSource, query: JobSearchQuery): Promise<JobProviderResult> { if (!countryAllowed(source, query)) return { provider: source.provider, status: "zero-results", jobs: [] }; const collected: NormalizedJob[] = []; const feeds = source.feedUrls ?? []; for (const feed of feeds) { try { const xml = await fetchText(feed); const jobs = parseFeed(xml, source).filter((job) => titleMatches(job.title, query.title)); collected.push(...jobs.slice(0, Math.min(query.limit ?? 50, 100))); } catch { /* feed failure should not prevent public-web collection */ } } if (source.mode.includes("web")) { for (const seed of source.seedUrls) { try { const html = await fetchText(seed); const structured = parseJsonLd(html).map((item) => parseJobPostingJsonLd(item, source.provider, source.name, seed)).filter(Boolean) as NormalizedJob[]; collected.push(...structured.filter((job) => titleMatches(job.title, query.title))); const links = extractCandidateLinks(html, seed, query); for (const link of links) { try { const detailHtml = await fetchText(link); const detailJobs = parseJsonLd(detailHtml).map((item) => parseJobPostingJsonLd(item, source.provider, source.name, link)).filter(Boolean) as NormalizedJob[]; collected.push(...detailJobs); } catch { /* continue collecting other public pages */ } } } catch { /* continue to other seeds */ } } }
 const deduped = new Map<string, NormalizedJob>(); for (const job of collected) { const key = `${job.title.toLowerCase()}|${job.companyName.toLowerCase()}|${(job.location ?? "").toLowerCase()}`; const old = deduped.get(key); deduped.set(key, old ? { ...old, description: (job.description?.length ?? 0) > (old.description?.length ?? 0) ? job.description : old.description, companyWebsite: old.companyWebsite ?? job.companyWebsite, companyDomain: old.companyDomain ?? job.companyDomain, applyUrl: old.applyUrl ?? job.applyUrl, postedAt: old.postedAt ?? job.postedAt, verificationReasons: Array.from(new Set([...old.verificationReasons, ...job.verificationReasons])) } : job); }
 const jobs = Array.from(deduped.values()).slice(0, query.limit ?? 50); return { provider: source.provider, status: jobs.length ? "success" : "zero-results", jobs, totalCount: jobs.length, hasMore: false }; }

export async function scrapeRegionalSource(provider: JobProvider, query: JobSearchQuery): Promise<JobProviderResult> { const source = REGIONAL_JOB_SOURCES.find((item) => item.provider === provider); if (!source) return { provider, status: "unavailable", jobs: [], errorMessage: "Regional source is not configured." }; return scrapeSource(source, query); }
