import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/auth/middleware";
import { runMarketJobDiscovery } from "@/providers/jobs/market-router";
import { persistJobs } from "@/providers/jobs/persistence";
import { deterministicIntelligence } from "@/services/jobs/analysis";
import { recordJobSearchHistory } from "@/services/jobs/search-history";
import { researchJobs } from "@/services/jobs/source-research";
import { resolveApplicationAndContactsBatch } from "@/services/jobs/application-resolver";
import type { AnyJobProvider, JobProvider, JobProviderResult, JobSearchQuery, NormalizedJob, RegionalJobProvider } from "@/providers/jobs/types";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
const GLOBAL_PROVIDERS: JobProvider[] = ["adzuna", "jsearch", "jobspipe", "hirebase", "theirstack"];
const ALL_REGIONAL: RegionalJobProvider[] = ["myjobmag", "jobberman", "hotnigerianjobs", "jobgurus", "jobsinnigeria", "workinnigeria", "fuzu", "careerjet", "brightermonday", "careers24", "careerjunction", "pnet"];
const REGIONAL_BY_COUNTRY: Record<string, RegionalJobProvider[]> = { NG: ["myjobmag", "jobberman", "hotnigerianjobs", "jobgurus", "jobsinnigeria", "workinnigeria", "fuzu", "careerjet"], GH: ["myjobmag", "jobberman", "fuzu", "brightermonday", "careerjet"], KE: ["myjobmag", "fuzu", "brightermonday", "careerjet"], UG: ["fuzu", "brightermonday"], ZA: ["myjobmag", "careerjet", "careers24", "careerjunction", "pnet"] };
type ProviderState = { provider: AnyJobProvider; status: "queued" | "searching" | "researching" | "complete" | "failed"; count: number; researched?: number; totalCount?: number; nextCursor?: string; hasMore?: boolean; errorMessage?: string };
type StreamEvent = { type: "status"; message: string; providers: ProviderState[] } | { type: "provider"; provider: AnyJobProvider; result: JobProviderResult | { provider: AnyJobProvider; status: string; jobs: NormalizedJob[]; totalCount?: number; errorMessage?: string }; jobs: NormalizedJob[]; providers: ProviderState[] } | { type: "complete"; jobs: NormalizedJob[]; providers: ProviderState[]; diagnostics: Record<string, unknown>; pagination: Record<string, { totalCount?: number; nextCursor?: string; hasMore: boolean }> };
function jsonLine(event: StreamEvent) { return `${JSON.stringify(event)}\n`; }
function normalizeIdentity(value?: string) { return (value ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").replace(/\s+/g, " ").trim(); }
function jobIdentityKey(job: NormalizedJob) { return `${normalizeIdentity(job.companyDomain ?? job.companyName)}|${normalizeIdentity(job.title)}|${normalizeIdentity(job.city ?? job.location ?? job.countryCode ?? "")}|${job.remote ? "remote" : "onsite"}`; }
function mergeJobs(current: NormalizedJob[], incoming: NormalizedJob[]) { const byIdentity = new Map(current.map((job) => [jobIdentityKey(job), job])); for (const job of incoming) { const key = jobIdentityKey(job); const existing = byIdentity.get(key); if (!existing) { byIdentity.set(key, job); continue; } byIdentity.set(key, { ...existing, ...job, id: existing.id, description: (job.description?.length ?? 0) > (existing.description?.length ?? 0) ? job.description : existing.description, requirements: Array.from(new Set([...(existing.requirements ?? []), ...(job.requirements ?? [])])).slice(0, 16), companyPhone: job.companyPhone ?? existing.companyPhone, companyEmail: job.companyEmail ?? existing.companyEmail, companyWebsite: job.companyWebsite ?? existing.companyWebsite, companyDomain: job.companyDomain ?? existing.companyDomain, applyUrl: job.applyUrl ?? existing.applyUrl, sourceUrl: job.sourceUrl ?? existing.sourceUrl, sourceName: existing.sourceName ?? job.sourceName, verificationStatus: job.verificationScore != null || job.verificationStatus !== "unverified" ? job.verificationStatus : existing.verificationStatus, verificationScore: job.verificationScore ?? existing.verificationScore, verificationReasons: job.verificationReasons.length ? job.verificationReasons : existing.verificationReasons, verificationEvidence: job.verificationEvidence ?? existing.verificationEvidence }); } return Array.from(byIdentity.values()); }
function withIntelligence(jobs: NormalizedJob[]) { return jobs.map((job) => ({ ...job, intelligence: deterministicIntelligence(job) })); }
function evidenceReady(job: NormalizedJob) { return Boolean(job.companyWebsite || job.applyUrl || job.companyPhone || job.companyEmail || job.verificationEvidence?.length); }
function selectedProviders(value: unknown, countryCode: string): AnyJobProvider[] { const requested = Array.isArray(value) ? value.filter((item): item is AnyJobProvider => typeof item === "string" && ([...GLOBAL_PROVIDERS, ...ALL_REGIONAL] as string[]).includes(item)) : []; return requested.length ? Array.from(new Set(requested)) : [...(REGIONAL_BY_COUNTRY[countryCode] ?? []), ...GLOBAL_PROVIDERS]; }

export async function POST(request: NextRequest) {
  const auth = await requireAuth(request); if (auth instanceof NextResponse) return auth;
  const body = await request.json().catch(() => null) as Record<string, unknown> | null;
  const title = typeof body?.title === "string" ? body.title.trim() : ""; if (!title) return NextResponse.json({ error: "Job title or search terms are required." }, { status: 400 });
  const limitRaw = Number(body?.limit ?? 50); const limit = Math.max(1, Math.min(Number.isFinite(limitRaw) ? Math.floor(limitRaw) : 50, 100));
  const pageRaw = Number(body?.page ?? 1); const page = Math.max(1, Math.min(Number.isFinite(pageRaw) ? Math.floor(pageRaw) : 1, 100));
  const countryCode = typeof body?.countryCode === "string" ? body.countryCode.trim().toUpperCase() : "NG";
  const country = typeof body?.country === "string" ? body.country.trim() : undefined; const city = typeof body?.city === "string" ? body.city.trim() : undefined; const remote = typeof body?.remote === "boolean" ? body.remote : undefined; const directOnly = typeof body?.directOnly === "boolean" ? body.directOnly : false;
  const postedWithinDaysRaw = Number(body?.postedWithinDays ?? 30); const postedWithinDays = Number.isFinite(postedWithinDaysRaw) ? Math.max(1, Math.min(Math.floor(postedWithinDaysRaw), 90)) : 30;
  const cursors = body?.cursors && typeof body.cursors === "object" ? body.cursors as Record<string, unknown> : {};
  const providers = selectedProviders(body?.providers, countryCode); const query: JobSearchQuery = { title, country, countryCode, city, remote, directOnly, limit, postedWithinDays, page, cursor: typeof cursors.jsearch === "string" ? cursors.jsearch : undefined };
  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({ async start(controller) {
    let closed = false; const write = (event: StreamEvent) => { if (!closed) controller.enqueue(encoder.encode(jsonLine(event))); }; const states: ProviderState[] = providers.map((provider) => ({ provider, status: "queued", count: 0, researched: 0 })); const stateMap = new Map(states.map((state) => [state.provider, state])); let cumulative: NormalizedJob[] = [];
    const priorityPerProvider = Math.max(1, Math.min(Number(process.env.JOB_STREAM_PRIORITY_RESEARCH_PER_PROVIDER) || 2, 4));
    try {
      write({ type: "status", message: "Vantage is connecting directly to Nigerian and regional job sources, then resolving employer evidence.", providers: states });
      await Promise.all(providers.map(async (provider) => { const state = stateMap.get(provider)!; state.status = "searching"; write({ type: "status", message: `Vantage is collecting from ${provider}.`, providers: states }); let result: JobProviderResult | { provider: AnyJobProvider; status: string; jobs: NormalizedJob[]; totalCount?: number; errorMessage?: string }; try { const discovery = await runMarketJobDiscovery(query, [provider], { verify: false }); const summary = discovery.providers.find((item) => item.provider === provider); const providerJobs = discovery.jobs.filter((job) => job.provider === provider); const providerPage = discovery.pagination[provider as keyof typeof discovery.pagination]; result = { provider, status: summary?.status ?? (providerJobs.length ? "success" : "zero-results"), jobs: providerJobs, totalCount: summary?.totalCount ?? providerPage?.totalCount ?? undefined, errorMessage: summary?.errorMessage }; } catch (error) { result = { provider, status: "failed", jobs: [], errorMessage: error instanceof Error ? error.message : "Provider request failed." }; }
        const incoming = withIntelligence(result.jobs); cumulative = mergeJobs(cumulative, incoming); state.count = result.jobs.length; state.totalCount = result.totalCount; state.nextCursor = (result as any).nextCursor; state.hasMore = Boolean((result as any).hasMore); state.errorMessage = result.errorMessage; try { if (incoming.length) await persistJobs(incoming, auth); } catch (error) { console.error(JSON.stringify({ diagnostic: "jobs_stream_persistence_failed", provider, message: error instanceof Error ? error.message : String(error) })); }
        write({ type: "provider", provider, result, jobs: cumulative, providers: states });
        if (result.jobs.length && result.status === "success") { state.status = "researching"; write({ type: "status", message: `Vantage found ${result.jobs.length} ${provider} listings and is resolving employer sources, application paths, and public contacts.`, providers: states }); try { const priorityJobs = result.jobs.filter((job) => !job.applyUrl || !job.companyWebsite || !job.companyPhone || !job.companyEmail).slice(0, priorityPerProvider); const researched = await researchJobs(priorityJobs, priorityJobs.length); const resolved = await resolveApplicationAndContactsBatch(researched, 2); const enriched = withIntelligence(resolved); state.researched = enriched.length; cumulative = mergeJobs(cumulative, enriched); if (enriched.length) await persistJobs(enriched, auth); write({ type: "provider", provider, result: { ...result, jobs: enriched }, jobs: cumulative, providers: states }); } catch (error) { state.errorMessage = state.errorMessage ?? (error instanceof Error ? error.message : "Priority source research failed."); } }
        state.status = result.status === "failed" || result.status === "rate-limited" ? "failed" : "complete"; write({ type: "status", message: `${provider} is complete.`, providers: states });
      }));
      const pagination: Record<string, { totalCount?: number; nextCursor?: string; hasMore: boolean }> = {}; for (const provider of providers) { const state = stateMap.get(provider)!; pagination[provider] = { totalCount: state.totalCount, nextCursor: state.nextCursor, hasMore: Boolean(state.hasMore) }; }
      try { await recordJobSearchHistory({ query: title, countryCode, country, city, remote, directOnly, postedWithinDays, providers: providers.map(String), resultCount: cumulative.length }, auth); } catch (error) { console.error(JSON.stringify({ diagnostic: "job_search_history_record_failed", message: error instanceof Error ? error.message : String(error) })); }
      const failures = states.filter((state) => state.status === "failed").length; const ready = cumulative.filter(evidenceReady).length; write({ type: "complete", jobs: cumulative, providers: states, pagination, diagnostics: { providersFailed: failures, providersConfigured: providers.length, rawProviderHits: states.reduce((sum, state) => sum + state.count, 0), dedupedReturned: cumulative.length, providerAdvertisedTotals: states.reduce((sum, state) => sum + (state.totalCount ?? 0), 0), returned: cumulative.length, applicationPaths: cumulative.filter((job) => Boolean(job.applyUrl)).length, employerSources: cumulative.filter((job) => Boolean(job.companyWebsite)).length, employerContacts: cumulative.filter((job) => Boolean(job.companyPhone || job.companyEmail)).length, evidenceReady: ready, aiAnalyzed: 0 } });
    } catch (error) { try { await recordJobSearchHistory({ query: title, countryCode, country, city, remote, directOnly, postedWithinDays, providers: providers.map(String), resultCount: cumulative.length }, auth); } catch {} write({ type: "complete", jobs: cumulative, providers: states, pagination: {}, diagnostics: { streamError: error instanceof Error ? error.message : String(error), returned: cumulative.length, evidenceReady: cumulative.filter(evidenceReady).length } }); } finally { closed = true; controller.close(); }
  }});
  return new Response(stream, { status: 200, headers: { "Content-Type": "application/x-ndjson; charset=utf-8", "Cache-Control": "no-store, no-cache, must-revalidate", "X-Accel-Buffering": "no" } });
}
